services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: User
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  api:
    build: .
    container_name: microservicio_login
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: usuario   
      DB_PASSWORD: 123   
      DB_NAME: User
      DB_PORT: 3306
    ports:
      - "3000:3000"
    command: ["node", "login.js"]
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
